=== pipina/urso-service-be/urso_be/urso-common/definitions/registerPluginConfig_v1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.dominanz.sk/registerPluginConfig_v1"
	xmlns:tns="http://www.dominanz.sk/registerPluginConfig_v1"
	xmlns:clb="http://www.dominanz.sk/UVZ/Reg/CodeListBase"
	elementFormDefault="qualified">

	<import namespace="http://www.dominanz.sk/UVZ/Reg/CodeListBase"
		schemaLocation="codelistBase_v1.xsd" />

	<import schemaLocation="codelistBase_v1.xsd"
			namespace="http://www.dominanz.sk/UVZ/Reg/CodeListBase"/>
	<element name="RegisterPluginConfig"
			 type="tns:RegisterPluginConfig"/>

	<complexType name="RegisterPluginConfig">
		<sequence>
			<element name="Field" type="tns:RegisterEntryField"
				maxOccurs="unbounded" minOccurs="1">
			</element>
			<element name="RegisterType" maxOccurs="1" minOccurs="1">
				<simpleType>
					<restriction base="string">
						<enumeration value="INTERNAL"/>
						<enumeration value="EXTERNAL"/>
					</restriction>
				</simpleType>
			</element>
			<element name="IntegrationParams"
				type="tns:IntegrationParams" maxOccurs="1" minOccurs="0">
			</element>
			<element name="MDMParams" type="tns:MDMParams" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="GdprParams" type="tns:GdprParams"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="Validations" type="tns:Validation"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="XsdFile" type="tns:XsdFile"
				maxOccurs="unbounded" minOccurs="1">
			</element>
			<element name="FormioField" type="tns:FormioFieldType"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="UseNaturalIdTable" type="boolean" use="optional" default="false"/>
	</complexType>

	<complexType name="RegisterEntryField">
		<complexContent>
			<extension base="tns:XPathNamedKey">


				<choice>
					<element name="Enumeration"
						type="tns:EnumerationField" minOccurs="0" maxOccurs="1">
					</element>
					<element name="Register" type="tns:RegisterField"
						maxOccurs="1" minOccurs="0">
					</element>
					<element name="Historical"
						type="tns:HistoricalField" maxOccurs="1" minOccurs="0">
					</element>
				</choice>
				<attribute name="Description" type="string"
					use="optional">
				</attribute>

				<attribute name="ValueType" use="optional"
					default="STRING">
					<simpleType>
						<restriction base="tns:ValueType">
							<enumeration value="STRING" />
							<enumeration value="DATE" />
							<enumeration value="TIME" />
							<enumeration value="DATETIME" />
							<enumeration value="NUMBER" />
						</restriction>
					</simpleType>
				</attribute>

				<attribute name="IsFunction" type="boolean"
					use="optional" default="false">
					<annotation>
						<documentation>
							if true, XPath is describing function - only
							one value is returned, otherwise node list
							can be returned - multiple values can be
							returned!
						</documentation>
					</annotation>
				</attribute>
				<attribute name="IsIndexed" type="boolean"
					use="optional" default="false">
					<annotation>
						<documentation>
							If true, this field is indexed - it is
							prepared for search and we donot have to
							execute xpath to obtain a value.
						</documentation>
					</annotation>
				</attribute>
				<attribute name="IsOutputField" type="boolean"
					use="optional" default="false">
					<annotation>
						<documentation>
							If true this field is returned in register
							entry output - for search and similar
							operations.
						</documentation>
					</annotation>
				</attribute>
				<attribute name="DisplayName" type="string"
					use="optional">
					<annotation>
						<documentation>
							Lokalizovaný názov tohto poľa
						</documentation>
					</annotation>
				</attribute>
				<attribute name="IsId" type="boolean" use="optional"
					default="false" />
				<attribute name="IsIdGenerated" type="boolean"
					use="optional" default="true">
				</attribute>
				<attribute name="SearchType" use="optional" default="LIKE">
                    <annotation>
                    	<documentation>Určuje či sa hodnota má hľadať cez LIKE alebo cez EQUALS. 
Default hodnota LIKE.
Default hodnota sa ignoruje ak napr. vieme že pole je ID alebo číselníková hodnota - vtedy hľadáme cez EQUALS.</documentation>
                    </annotation>
                    <simpleType>
						<restriction base="string">
							<enumeration value="LIKE"></enumeration>
							<enumeration value="EQUALS"></enumeration>
						</restriction>
					</simpleType>
				</attribute>
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="ValueType">
		<restriction base="string"/>
	</simpleType>

	<complexType name="RegisterType"/>

	<complexType name="IntegrationParams">
		<sequence>
			<element name="SynchronousCall" type="tns:SynchronousCall"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="AsynchronousCall" type="tns:AsynchronousCall"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="AsyncCallbackId" type="string" maxOccurs="1"
					 minOccurs="1"/>
		</sequence>
	</complexType>

	<complexType name="SynchronousCall">
		<sequence>
			<element name="InputToKey" type="tns:XPathNamedKey"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="InputXsdFile" type="string"></attribute>
		<attribute name="OutputXsdFile" type="string"></attribute>
		<attribute name="InputClassName" type="string"></attribute>
		<attribute name="OutputClassName" type="string"></attribute>
	</complexType>

	<complexType name="XPathNamedKey">
		<attribute name="KeyName" type="tns:KeyNameType" use="optional"></attribute>
		<attribute name="XPathValue" type="string" use="required"></attribute>
	</complexType>

	<complexType name="AsynchronousCall">
		<sequence>
			<element name="InputToKey" type="tns:XPathNamedKey"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="InputXsdFile" type="string"></attribute>
		<attribute name="OutputXsdFile" type="string"></attribute>
		<attribute name="InputClassName" type="string"></attribute>
		<attribute name="OutputClassName" type="string"></attribute>
	</complexType>

	<complexType name="MDMParams"></complexType>

	<complexType name="UIParams"></complexType>

	<complexType name="GdprParams">
		<attribute name="IsGdprRelevant" type="boolean"
			use="required">
            <annotation>
            	<documentation>If true entries are deleted aut0matically when there is no reference to entry.</documentation>
            </annotation>
		</attribute>
		<attribute name="ImmediateDeleteOnLastReference" type="boolean"
			use="optional">
            <annotation>
            	<documentation>If true, entry is deleted immediately after last reference is removed.</documentation>
            </annotation>
		</attribute>
		<attribute name="TTL" use="optional">
			<annotation>
				<documentation>
					Time after entry is deleted when without references.
					This is used for entries inserted after search (so
					they have no references yet) or after last reference
					is removed from entry and immediate delete is not
					set.
				</documentation>
			</annotation>
			<simpleType>
				<restriction base="int">
					<minInclusive value="1"></minInclusive>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="TTLUnit" use="optional">
            <annotation>
            	<documentation>Unit of TTL</documentation>
            </annotation>
            <simpleType>
				<restriction base="string">
					<enumeration value="YEARS"></enumeration>
					<enumeration value="MONTHS"></enumeration>
					<enumeration value="WEEKS"></enumeration>
					<enumeration value="DAYS"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="Validation">
		<sequence>
			<element name="Field" type="tns:ValidatedField"></element>
		</sequence>
	</complexType>

	<complexType name="ValidatedField">
		<sequence>
		</sequence>
		<attribute name="ValueXPath" type="string"></attribute>
	</complexType>

	<complexType name="ValidatedFieldReference">
		<choice>
			<element name="Enumeration" type="tns:EnumerationReference"></element>
			<element name="Register" type="tns:RegisterReference"></element>
		</choice>
	</complexType>

	<complexType name="EnumerationReference">
		<attribute name="CodelistCode" type="clb:codeListCodeType"></attribute>
	</complexType>

	<complexType name="RegisterReference">
		<attribute name="RegisterId" type="string"></attribute>
		<attribute name="KeyName" type="string"></attribute>
	</complexType>

	<complexType name="XsdFile">
		<attribute name="IsPrimary" type="boolean" use="required"></attribute>
		<attribute name="Path" type="string" use="required"></attribute>
		<attribute name="IsExternal" type="boolean" use="required"></attribute>
		<attribute name="NamespacePrefix" type="string" use="optional"></attribute>
		<attribute name="NamespaceUrl" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="EnumerationField">
		<attribute name="CodelistCode" type="clb:codeListCodeType" use="required"></attribute>
		<attribute name="IsItemCodeRequired" type="boolean"
					use="optional" default="true">
					<annotation>
						<documentation>
							If true this field is required in data.
						</documentation>
					</annotation>
				</attribute>
	</complexType>

	<complexType name="RegisterField">
		<sequence>
			<element name="RegisterJoinKey" type="tns:RegisterJoinKeyType" maxOccurs="1" minOccurs="1"></element>
		</sequence>
		<attribute name="RegisterId" use="required">
			<simpleType>
				<restriction base="string">
					<minLength value="1"></minLength>
					<maxLength value="256"></maxLength>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="Version" use="required">
			<simpleType>
				<restriction base="int">
					<minInclusive value="1"></minInclusive>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<simpleType name="KeyNameType">
		<restriction base="string">
			<minLength value="1"></minLength>
			<maxLength value="256"></maxLength>
		</restriction>
	</simpleType>

	<complexType name="RegisterJoinKeyType">
		<sequence></sequence>
		<attribute name="Source" type="tns:KeyNameType" use="required"></attribute>
		<attribute name="Target" type="tns:KeyNameType" use="required"></attribute>
	</complexType>

	<attribute name="NewAttribute" type="string"></attribute>



	<complexType name="FormioFieldType">
		<sequence>
			<element name="Custom" type="tns:CustomFormioExpressionType" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
		<attribute name="Name" type="string" use="required">
			<annotation>
				<documentation>Obsahuje formio key pola na ktore sa konfiguracia stahuje</documentation>
			</annotation></attribute>
		<attribute name="Path" type="string" use="optional">
			<annotation>
				<documentation>Obsahuje cestu k formio polu (viacero poli moze mat rovnaky formio Key)</documentation>
			</annotation></attribute>
		<attribute name="DefaultValue" type="string" use="optional"></attribute>
		<attribute name="IsGenerated" type="boolean" use="optional"
			default="false">
		</attribute>
		<attribute name="IsUpdatable" type="boolean" use="optional" default="true"></attribute>
	</complexType>

	<complexType name="CustomFormioExpressionType">
		<attribute name="Mark" use="required">
			<annotation>
				<documentation>
					Oznacuje aku formio property nastavit
				</documentation>
			</annotation>
			<simpleType>
				<restriction
					base="tns:CustomFormioExpressionMarkType">
					<enumeration value="valid"></enumeration>
					<enumeration value="show"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
        <attribute name="As" type="boolean" use="optional" default="true"></attribute>
        <attribute name="WhenField" type="string" use="optional"></attribute>
		<attribute name="Equals" type="string" use="optional"></attribute>
		<attribute name="ErrorMessage" type="string" use="optional"></attribute>
		<attribute name="Custom" type="string" use="optional"></attribute>
	</complexType>

	<simpleType name="CustomFormioExpressionMarkType">
		<restriction base="string"></restriction>
	</simpleType>

	<complexType name="HistoricalField">
		<attribute name="CurrentMax" type="int" use="optional"></attribute>
	</complexType>
</schema>

=== pipina/urso-service-be/urso_be/urso-common/configuration/RA_INTERNAL_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:RegisterPluginConfig
	xmlns:tns="http://www.dominanz.sk/registerPluginConfig_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dominanz.sk/registerPluginConfig_v1 ../definitions/registerPluginConfig_v1.xsd">
	<tns:Field KeyName="addressType" XPathValue="ns0:Address/type"
		IsIndexed="true" IsOutputField="true" DisplayName="Typ" Description="Typ adresy.">
	</tns:Field>
	<tns:Field KeyName="objectId" XPathValue="ns0:Address/objectId"
	    IsId="true" IsIndexed="true" IsOutputField="true" DisplayName="Id" Description="Id objektu." IsIdGenerated="false">
	</tns:Field>
	<tns:Field KeyName="RegionItemCode" XPathValue="ns0:Address/data/change/regionChange/Region/Codelist/CodelistItem/ItemCode"
		IsIndexed="true" IsOutputField="true" DisplayName="Kraj" Description="Kraj.">
<!-- 		<tns:Enumeration CodelistCode="CUREG000006"/> -->
	</tns:Field>
	<tns:Field KeyName="RegionItemName" XPathValue="ns0:Address/data/change/regionChange/Region/Codelist/CodelistItem/ItemName"
		IsIndexed="true" IsOutputField="true" DisplayName="Kraj" Description="Kraj.">
	</tns:Field>
	<tns:Field KeyName="RegionItemName" XPathValue="ns0:Address/data/change/regionChange/Region/NonCodelistData"
			   IsIndexed="true" IsOutputField="true" DisplayName="Kraj" Description="Kraj.">
	</tns:Field>
	<tns:Field KeyName="CountyItemCode" XPathValue="ns0:Address/data/change/countyChange/County/Codelist/CodelistItem/ItemCode"
			   IsIndexed="true" IsOutputField="true" DisplayName="Okres" Description="Okres.">
<!-- 		<tns:Enumeration CodelistCode="CUREG000007"/> -->
	</tns:Field>
	<tns:Field KeyName="CountyItemName" XPathValue="ns0:Address/data/change/countyChange/County/Codelist/CodelistItem/ItemName"
			   IsIndexed="true" IsOutputField="true" DisplayName="Okres" Description="Okres.">
	</tns:Field>
	<tns:Field KeyName="CountyItemName" XPathValue="ns0:Address/data/change/countyChange/County/NonCodelistData"
			   IsIndexed="true" IsOutputField="true" DisplayName="Okres" Description="Okres.">
	</tns:Field>
	<tns:Field KeyName="regionId" XPathValue="ns0:Address/data/change/countyChange/regionIdentifier"
			   IsIndexed="true" IsOutputField="true" DisplayName="Id kraja" Description="Id kraja.">
		<tns:Register RegisterId="RA_INTERNAL" Version="1">
			<tns:RegisterJoinKey  Source="regionId" Target="objectId"/>
		</tns:Register>
	</tns:Field>
	<tns:Field KeyName="MunicipalityItemCode" XPathValue="ns0:Address/data/change/municipalityChange/Municipality/Codelist/CodelistItem/ItemCode"
			   IsIndexed="true" IsOutputField="true" DisplayName="Obec" Description="Obec.">
<!-- 		<tns:Enumeration CodelistCode="CUREG000005"/> -->
	</tns:Field>
	<tns:Field KeyName="MunicipalityItemName" XPathValue="ns0:Address/data/change/municipalityChange/Municipality/Codelist/CodelistItem/ItemName"
			   IsIndexed="true" IsOutputField="true" DisplayName="Obec" Description="Obec.">
	</tns:Field>
	<tns:Field KeyName="MunicipalityItemName" XPathValue="ns0:Address/data/change/municipalityChange/Municipality/NonCodelistData"
			   IsIndexed="true" IsOutputField="true" DisplayName="Obec" Description="Obec.">
	</tns:Field>
	<tns:Field KeyName="countyId" XPathValue="ns0:Address/data/change/municipalityChange/countyIdentifier"
			   IsIndexed="true" IsOutputField="true" DisplayName="Id okresu" Description="Id okresu.">
		<tns:Register RegisterId="RA_INTERNAL" Version="1">
			<tns:RegisterJoinKey  Source="countyId" Target="objectId"/>
		</tns:Register>
	</tns:Field>
	<tns:Field KeyName="DistrictItemCode" XPathValue="ns0:Address/data/change/districtChange/District/Codelist/CodelistItem/ItemCode"
			   IsIndexed="true" IsOutputField="true" DisplayName="Obvod" Description="Obvod.">
<!-- 		<tns:Enumeration CodelistCode="CL010141"/> -->
	</tns:Field>
	<tns:Field KeyName="DistrictItemName" XPathValue="ns0:Address/data/change/districtChange/District/Codelist/CodelistItem/ItemName"
			   IsIndexed="true" IsOutputField="true" DisplayName="Obvod" Description="Obvod.">
	</tns:Field>
	<tns:Field KeyName="DistrictItemName" XPathValue="ns0:Address/data/change/districtChange/District/NonCodelistData"
			   IsIndexed="true" IsOutputField="true" DisplayName="Obvod" Description="Obvod.">
	</tns:Field>
	<tns:Field KeyName="municipalityId" XPathValue="ns0:Address/data/change/districtChange/municipalityIdentifier"
			   IsIndexed="true" IsOutputField="true" DisplayName="Id obce" Description="Id obce.">
		<tns:Register RegisterId="RA_INTERNAL" Version="1">
			<tns:RegisterJoinKey  Source="municipalityId" Target="objectId"/>
		</tns:Register>
	</tns:Field>
	<tns:Field KeyName="StreetName" XPathValue="ns0:Address/data/change/streetNameChange/StreetName"
		IsIndexed="true" IsOutputField="true" DisplayName="Ulica" Description="Názov ulice.">
	</tns:Field>
	<tns:Field KeyName="municipalityId" XPathValue="ns0:Address/data/change/streetNameChange/municipalityIdentifier"
			   IsIndexed="true" IsOutputField="true" DisplayName="Id obce" Description="Id obce.">
		<tns:Register RegisterId="RA_INTERNAL" Version="1">
			<tns:RegisterJoinKey  Source="municipalityId" Target="objectId"/>
		</tns:Register>
	</tns:Field>
	<tns:Field KeyName="districtId" XPathValue="ns0:Address/data/change/streetNameChange/districtIdentifier"
			   IsIndexed="true" IsOutputField="true" DisplayName="Id obvodu" Description="Id obvodu.">
		<tns:Register RegisterId="RA_INTERNAL" Version="1">
			<tns:RegisterJoinKey  Source="districtId" Target="objectId"/>
		</tns:Register>
	</tns:Field>
	<tns:Field KeyName="PropertyRegistrationNumber" ValueType="NUMBER" XPathValue="ns0:Address/data/change/propertyRegistrationNumberChange/PropertyRegistrationNumber"
			   IsIndexed="true" IsOutputField="true" DisplayName="Súpisné číslo" Description="Súpisné číslo.">
	</tns:Field>
	<tns:Field KeyName="municipalityId" XPathValue="ns0:Address/data/change/propertyRegistrationNumberChange/municipalityIdentifier"
			   IsIndexed="true" IsOutputField="true" DisplayName="Id obce" Description="Id obce.">
		<tns:Register RegisterId="RA_INTERNAL" Version="1">
			<tns:RegisterJoinKey  Source="municipalityId" Target="objectId"/>
		</tns:Register>
	</tns:Field>
	<tns:Field KeyName="districtId" XPathValue="ns0:Address/data/change/propertyRegistrationNumberChange/districtIdentifier"
			   IsIndexed="true" IsOutputField="true" DisplayName="Id obvodu" Description="Id obvodu.">
		<tns:Register RegisterId="RA_INTERNAL" Version="1">
			<tns:RegisterJoinKey  Source="districtId" Target="objectId"/>
		</tns:Register>
	</tns:Field>
	<tns:Field KeyName="BuildingIndex" XPathValue="ns0:Address/data/change/buildingNumberChange/BuildingIndex"
			   IsIndexed="true" IsOutputField="true" DisplayName="Index budovy" Description="Index budovy.">
	</tns:Field>
	<tns:Field KeyName="PostalCode" XPathValue="ns0:Address/data/change/buildingNumberChange/PostalCode"
			   IsIndexed="true" IsOutputField="true" DisplayName="PSČ" Description="PSČ.">
	</tns:Field>
	<tns:Field KeyName="BuildingNumber" XPathValue="ns0:Address/data/change/buildingNumberChange/BuildingNumber"
		IsIndexed="true" IsOutputField="true" DisplayName="Číslo budovy" Description="Číslo budovy">
	</tns:Field>
	<tns:Field KeyName="PropertyRegistrationNumberIdr" XPathValue="ns0:Address/data/change/buildingNumberChange/propertyRegistrationNumberIdentifier"
		IsIndexed="true" IsOutputField="true" DisplayName="Číslo budovy" Description="Číslo budovy">
	</tns:Field>
	<tns:Field KeyName="streetNameId" XPathValue="ns0:Address/data/change/buildingNumberChange/streetNameId"
			   IsIndexed="true" IsOutputField="true" DisplayName="Id ulice" Description="Id názvu ulice.">
		<tns:Register RegisterId="RA_INTERNAL" Version="1">
			<tns:RegisterJoinKey  Source="streetNameId" Target="objectId"/>
		</tns:Register>
	</tns:Field>
	<tns:Field KeyName="BuildingUnit" XPathValue="ns0:Address/data/change/buildingUnitChange/BuildingUnit/UnitNumber"
			   IsIndexed="true" IsOutputField="true" DisplayName="PSČ" Description="PSČ">
	</tns:Field>
	<tns:Field KeyName="BuildingNumberId" XPathValue="ns0:Address/data/change/buildingUnitChange/buildingNumberIdentifier"
			   IsIndexed="true" IsOutputField="true" DisplayName="PSČ" Description="PSČ">
		<tns:Register RegisterId="RA_INTERNAL" Version="1">
			<tns:RegisterJoinKey  Source="BuildingNumberId" Target="objectId"/>
		</tns:Register>
	</tns:Field>
	<tns:Field XPathValue="ns0:Address/data">
		<tns:Historical/>
	</tns:Field>

	<tns:RegisterType>EXTERNAL</tns:RegisterType>
	<tns:GdprParams IsGdprRelevant="false" ImmediateDeleteOnLastReference="false" TTL="1" TTLUnit="DAYS"/>
	<tns:XsdFile IsPrimary="true" Path="RA_INTERNAL_1/RA_INTERNAL_1_DATA.xsd" IsExternal="true" NamespacePrefix="ns0" NamespaceUrl="http://www.minv.sk/ra"/>
	<tns:XsdFile IsPrimary="false" Path="RA_INTERNAL_1/RA_INTERNAL_1_TYPES.xsd" IsExternal="true" NamespacePrefix="" NamespaceUrl="http://www.minv.sk/ra"/>
</tns:RegisterPluginConfig>

=== pipina/urso-service-be/urso_be/urso-common/configuration/RA_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:RegisterPluginConfig
	xmlns:tns="http://www.dominanz.sk/registerPluginConfig_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dominanz.sk/registerPluginConfig_v1 ../definitions/registerPluginConfig_v1.xsd">
	<tns:Field KeyName="RegionItemName" XPathValue="ad:Address/Region/NonCodelistData"
		IsIndexed="true" IsOutputField="true" DisplayName="Okres" Description="Okres.">
	</tns:Field>
	<tns:Field KeyName="RegionItemName" XPathValue="ad:Address/Region/Codelist/CodelistItem/ItemName"
		IsIndexed="true" IsOutputField="true" DisplayName="Okres" Description="Okres.">
	</tns:Field>
	<tns:Field KeyName="RegionItemCode" XPathValue="ad:Address/Region/Codelist/CodelistItem/ItemCode"
		IsIndexed="true" IsOutputField="true" DisplayName="Okres" Description="Okres.">
	</tns:Field>
	<tns:Field KeyName="CountyItemName" XPathValue="ad:Address/County/NonCodelistData"
		IsIndexed="true" IsOutputField="true" DisplayName="Kraj" Description="Kraj.">
	</tns:Field>
	<tns:Field KeyName="CountyItemName" XPathValue="ad:Address/County/Codelist/CodelistItem/ItemName"
		IsIndexed="true" IsOutputField="true" DisplayName="Kraj" Description="Kraj.">
	</tns:Field>
	<tns:Field KeyName="CountyItemCode" XPathValue="ad:Address/County/Codelist/CodelistItem/ItemCode"
		IsIndexed="true" IsOutputField="true" DisplayName="Kraj" Description="Kraj.">
	</tns:Field>
	<tns:Field KeyName="MunicipalityItemName" XPathValue="ad:Address/Municipality/NonCodelistData"
		IsIndexed="true" IsOutputField="true" DisplayName="Obec" Description="Obec.">
	</tns:Field>
	<tns:Field KeyName="MunicipalityItemName" XPathValue="ad:Address/Municipality/Codelist/CodelistItem/ItemName"
		IsIndexed="true" IsOutputField="true" DisplayName="Obec" Description="Obec.">
	</tns:Field>
	<tns:Field KeyName="MunicipalityItemCode" XPathValue="ad:Address/Municipality/Codelist/CodelistItem/ItemCode"
		IsIndexed="true" IsOutputField="true" DisplayName="Obec" Description="Obec." SearchType="EQUALS">
	</tns:Field>
	<tns:Field KeyName="StreetName" XPathValue="ad:Address/StreetName"
		IsIndexed="true" IsOutputField="true" DisplayName="Ulica" Description="Názov ulice.">
	</tns:Field>
	<tns:Field KeyName="BuildingNumber" XPathValue="ad:Address/BuildingNumber"
		IsIndexed="true" IsOutputField="true" DisplayName="Číslo budovy" Description="Číslo budovy.">
	</tns:Field>
	<tns:Field KeyName="PropertyRegistrationNumber" ValueType="NUMBER" XPathValue="ad:Address/PropertyRegistrationNumber"
		IsIndexed="true" IsOutputField="true" DisplayName="Súpisné číslo" Description="Súpisné číslo.">
	</tns:Field>
	<tns:Field KeyName="BuildingIndex" XPathValue="ad:Address/BuildingIndex"
		IsIndexed="true" IsOutputField="true" DisplayName="Index budovy" Description="Index budovy.">
	</tns:Field>
	<tns:RegisterType>EXTERNAL</tns:RegisterType>
	<tns:GdprParams IsGdprRelevant="true" ImmediateDeleteOnLastReference="false" TTL="1" TTLUnit="DAYS"/>
	<tns:XsdFile IsPrimary="true" Path="RA_1/RA_1_DATA.xsd" IsExternal="true" NamespacePrefix="ad" NamespaceUrl="http://www.dominanz.sk/UVZ/Reg/ADDRESS"/>
	<tns:XsdFile IsPrimary="false" Path="RA_1/RA_1_TYPES.xsd" IsExternal="true" NamespacePrefix="" NamespaceUrl="http://www.dominanz.sk/UVZ/Reg/ADDRESS"/>
</tns:RegisterPluginConfig>
