=== pipina/urso-service-be/urso_be/urso-common/definitions/registerPluginConfig_v1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.dominanz.sk/registerPluginConfig_v1"
	xmlns:tns="http://www.dominanz.sk/registerPluginConfig_v1"
	xmlns:clb="http://www.dominanz.sk/UVZ/Reg/CodeListBase"
	elementFormDefault="qualified">

	<import namespace="http://www.dominanz.sk/UVZ/Reg/CodeListBase"
		schemaLocation="codelistBase_v1.xsd" />

	<import schemaLocation="codelistBase_v1.xsd"
			namespace="http://www.dominanz.sk/UVZ/Reg/CodeListBase"/>
	<element name="RegisterPluginConfig"
			 type="tns:RegisterPluginConfig"/>

	<complexType name="RegisterPluginConfig">
		<sequence>
			<element name="Field" type="tns:RegisterEntryField"
				maxOccurs="unbounded" minOccurs="1">
			</element>
			<element name="RegisterType" maxOccurs="1" minOccurs="1">
				<simpleType>
					<restriction base="string">
						<enumeration value="INTERNAL"/>
						<enumeration value="EXTERNAL"/>
					</restriction>
				</simpleType>
			</element>
			<element name="IntegrationParams"
				type="tns:IntegrationParams" maxOccurs="1" minOccurs="0">
			</element>
			<element name="MDMParams" type="tns:MDMParams" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="GdprParams" type="tns:GdprParams"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="Validations" type="tns:Validation"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="XsdFile" type="tns:XsdFile"
				maxOccurs="unbounded" minOccurs="1">
			</element>
			<element name="FormioField" type="tns:FormioFieldType"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="UseNaturalIdTable" type="boolean" use="optional" default="false"/>
	</complexType>

	<complexType name="RegisterEntryField">
		<complexContent>
			<extension base="tns:XPathNamedKey">


				<choice>
					<element name="Enumeration"
						type="tns:EnumerationField" minOccurs="0" maxOccurs="1">
					</element>
					<element name="Register" type="tns:RegisterField"
						maxOccurs="1" minOccurs="0">
					</element>
					<element name="Historical"
						type="tns:HistoricalField" maxOccurs="1" minOccurs="0">
					</element>
				</choice>
				<attribute name="Description" type="string"
					use="optional">
				</attribute>

				<attribute name="ValueType" use="optional"
					default="STRING">
					<simpleType>
						<restriction base="tns:ValueType">
							<enumeration value="STRING" />
							<enumeration value="DATE" />
							<enumeration value="TIME" />
							<enumeration value="DATETIME" />
							<enumeration value="NUMBER" />
						</restriction>
					</simpleType>
				</attribute>

				<attribute name="IsFunction" type="boolean"
					use="optional" default="false">
					<annotation>
						<documentation>
							if true, XPath is describing function - only
							one value is returned, otherwise node list
							can be returned - multiple values can be
							returned!
						</documentation>
					</annotation>
				</attribute>
				<attribute name="IsIndexed" type="boolean"
					use="optional" default="false">
					<annotation>
						<documentation>
							If true, this field is indexed - it is
							prepared for search and we donot have to
							execute xpath to obtain a value.
						</documentation>
					</annotation>
				</attribute>
				<attribute name="IsOutputField" type="boolean"
					use="optional" default="false">
					<annotation>
						<documentation>
							If true this field is returned in register
							entry output - for search and similar
							operations.
						</documentation>
					</annotation>
				</attribute>
				<attribute name="DisplayName" type="string"
					use="optional">
					<annotation>
						<documentation>
							Lokalizovaný názov tohto poľa
						</documentation>
					</annotation>
				</attribute>
				<attribute name="IsId" type="boolean" use="optional"
					default="false" />
				<attribute name="IsIdGenerated" type="boolean"
					use="optional" default="true">
				</attribute>
				<attribute name="SearchType" use="optional" default="LIKE">
                    <annotation>
                    	<documentation>Určuje či sa hodnota má hľadať cez LIKE alebo cez EQUALS. 
Default hodnota LIKE.
Default hodnota sa ignoruje ak napr. vieme že pole je ID alebo číselníková hodnota - vtedy hľadáme cez EQUALS.</documentation>
                    </annotation>
                    <simpleType>
						<restriction base="string">
							<enumeration value="LIKE"></enumeration>
							<enumeration value="EQUALS"></enumeration>
						</restriction>
					</simpleType>
				</attribute>
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="ValueType">
		<restriction base="string"/>
	</simpleType>

	<complexType name="RegisterType"/>

	<complexType name="IntegrationParams">
		<sequence>
			<element name="SynchronousCall" type="tns:SynchronousCall"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="AsynchronousCall" type="tns:AsynchronousCall"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="AsyncCallbackId" type="string" maxOccurs="1"
					 minOccurs="1"/>
		</sequence>
	</complexType>

	<complexType name="SynchronousCall">
		<sequence>
			<element name="InputToKey" type="tns:XPathNamedKey"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="InputXsdFile" type="string"></attribute>
		<attribute name="OutputXsdFile" type="string"></attribute>
		<attribute name="InputClassName" type="string"></attribute>
		<attribute name="OutputClassName" type="string"></attribute>
	</complexType>

	<complexType name="XPathNamedKey">
		<attribute name="KeyName" type="tns:KeyNameType" use="optional"></attribute>
		<attribute name="XPathValue" type="string" use="required"></attribute>
	</complexType>

	<complexType name="AsynchronousCall">
		<sequence>
			<element name="InputToKey" type="tns:XPathNamedKey"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="InputXsdFile" type="string"></attribute>
		<attribute name="OutputXsdFile" type="string"></attribute>
		<attribute name="InputClassName" type="string"></attribute>
		<attribute name="OutputClassName" type="string"></attribute>
	</complexType>

	<complexType name="MDMParams"></complexType>

	<complexType name="UIParams"></complexType>

	<complexType name="GdprParams">
		<attribute name="IsGdprRelevant" type="boolean"
			use="required">
            <annotation>
            	<documentation>If true entries are deleted aut0matically when there is no reference to entry.</documentation>
            </annotation>
		</attribute>
		<attribute name="ImmediateDeleteOnLastReference" type="boolean"
			use="optional">
            <annotation>
            	<documentation>If true, entry is deleted immediately after last reference is removed.</documentation>
            </annotation>
		</attribute>
		<attribute name="TTL" use="optional">
			<annotation>
				<documentation>
					Time after entry is deleted when without references.
					This is used for entries inserted after search (so
					they have no references yet) or after last reference
					is removed from entry and immediate delete is not
					set.
				</documentation>
			</annotation>
			<simpleType>
				<restriction base="int">
					<minInclusive value="1"></minInclusive>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="TTLUnit" use="optional">
            <annotation>
            	<documentation>Unit of TTL</documentation>
            </annotation>
            <simpleType>
				<restriction base="string">
					<enumeration value="YEARS"></enumeration>
					<enumeration value="MONTHS"></enumeration>
					<enumeration value="WEEKS"></enumeration>
					<enumeration value="DAYS"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="Validation">
		<sequence>
			<element name="Field" type="tns:ValidatedField"></element>
		</sequence>
	</complexType>

	<complexType name="ValidatedField">
		<sequence>
		</sequence>
		<attribute name="ValueXPath" type="string"></attribute>
	</complexType>

	<complexType name="ValidatedFieldReference">
		<choice>
			<element name="Enumeration" type="tns:EnumerationReference"></element>
			<element name="Register" type="tns:RegisterReference"></element>
		</choice>
	</complexType>

	<complexType name="EnumerationReference">
		<attribute name="CodelistCode" type="clb:codeListCodeType"></attribute>
	</complexType>

	<complexType name="RegisterReference">
		<attribute name="RegisterId" type="string"></attribute>
		<attribute name="KeyName" type="string"></attribute>
	</complexType>

	<complexType name="XsdFile">
		<attribute name="IsPrimary" type="boolean" use="required"></attribute>
		<attribute name="Path" type="string" use="required"></attribute>
		<attribute name="IsExternal" type="boolean" use="required"></attribute>
		<attribute name="NamespacePrefix" type="string" use="optional"></attribute>
		<attribute name="NamespaceUrl" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="EnumerationField">
		<attribute name="CodelistCode" type="clb:codeListCodeType" use="required"></attribute>
		<attribute name="IsItemCodeRequired" type="boolean"
					use="optional" default="true">
					<annotation>
						<documentation>
							If true this field is required in data.
						</documentation>
					</annotation>
				</attribute>
	</complexType>

	<complexType name="RegisterField">
		<sequence>
			<element name="RegisterJoinKey" type="tns:RegisterJoinKeyType" maxOccurs="1" minOccurs="1"></element>
		</sequence>
		<attribute name="RegisterId" use="required">
			<simpleType>
				<restriction base="string">
					<minLength value="1"></minLength>
					<maxLength value="256"></maxLength>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="Version" use="required">
			<simpleType>
				<restriction base="int">
					<minInclusive value="1"></minInclusive>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<simpleType name="KeyNameType">
		<restriction base="string">
			<minLength value="1"></minLength>
			<maxLength value="256"></maxLength>
		</restriction>
	</simpleType>

	<complexType name="RegisterJoinKeyType">
		<sequence></sequence>
		<attribute name="Source" type="tns:KeyNameType" use="required"></attribute>
		<attribute name="Target" type="tns:KeyNameType" use="required"></attribute>
	</complexType>

	<attribute name="NewAttribute" type="string"></attribute>



	<complexType name="FormioFieldType">
		<sequence>
			<element name="Custom" type="tns:CustomFormioExpressionType" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
		<attribute name="Name" type="string" use="required">
			<annotation>
				<documentation>Obsahuje formio key pola na ktore sa konfiguracia stahuje</documentation>
			</annotation></attribute>
		<attribute name="Path" type="string" use="optional">
			<annotation>
				<documentation>Obsahuje cestu k formio polu (viacero poli moze mat rovnaky formio Key)</documentation>
			</annotation></attribute>
		<attribute name="DefaultValue" type="string" use="optional"></attribute>
		<attribute name="IsGenerated" type="boolean" use="optional"
			default="false">
		</attribute>
		<attribute name="IsUpdatable" type="boolean" use="optional" default="true"></attribute>
	</complexType>

	<complexType name="CustomFormioExpressionType">
		<attribute name="Mark" use="required">
			<annotation>
				<documentation>
					Oznacuje aku formio property nastavit
				</documentation>
			</annotation>
			<simpleType>
				<restriction
					base="tns:CustomFormioExpressionMarkType">
					<enumeration value="valid"></enumeration>
					<enumeration value="show"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
        <attribute name="As" type="boolean" use="optional" default="true"></attribute>
        <attribute name="WhenField" type="string" use="optional"></attribute>
		<attribute name="Equals" type="string" use="optional"></attribute>
		<attribute name="ErrorMessage" type="string" use="optional"></attribute>
		<attribute name="Custom" type="string" use="optional"></attribute>
	</complexType>

	<simpleType name="CustomFormioExpressionMarkType">
		<restriction base="string"></restriction>
	</simpleType>

	<complexType name="HistoricalField">
		<attribute name="CurrentMax" type="int" use="optional"></attribute>
	</complexType>
</schema>

=== pipina/urso-service-be/urso_be/cli/src/main/resources/configuration/RPO_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:RegisterPluginConfig
	xmlns:tns="http://www.dominanz.sk/registerPluginConfig_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dominanz.sk/registerPluginConfig_v1 ../definitions/registerPluginConfig_v1.xsd">
	<tns:Field KeyName="CorporateBodyFullName" XPathValue="po:PO/po:CorporateBodyFullName"
		IsIndexed="true" IsOutputField="true" DisplayName="Celý názov" Description="Celý názov právnickej osoby">
	</tns:Field>
	<tns:Field KeyName="identifierValue" XPathValue="po:PO/po:ID/cs:IdentifierValue"
		IsIndexed="true" IsOutputField="true" DisplayName="ID" Description="Identifikátor právnickej osoby">
	</tns:Field>
	<tns:Field KeyName="LegalForm" XPathValue="po:PO/po:LegalForm/cs:NonCodelistData"
			   IsIndexed="true" IsOutputField="true" DisplayName="Právna forma" Description="Právna forma subjektu">
	</tns:Field>
	<tns:Field KeyName="LegalForm" XPathValue="po:PO/po:LegalForm/cs:Codelist/cs:CodelistItem/cs:ItemName"
			   IsIndexed="true" IsOutputField="true" DisplayName="Právna forma" Description="Právna forma subjektu">
	</tns:Field>
	<tns:Field KeyName="SkNaceMain" XPathValue="po:PO/po:SkNaceMain/cs:NonCodelistData"
		IsIndexed="true" IsOutputField="true" DisplayName="SK NACE" Description="SK NACE">
	</tns:Field>
	<tns:Field KeyName="SkNaceMain" XPathValue="po:PO/po:SkNaceMain/cs:Codelist/cs:CodelistItem/cs:ItemName"
		IsIndexed="true" IsOutputField="true" DisplayName="SK NACE" Description="SK NACE">
	</tns:Field>
	<tns:Field KeyName="AddressLine" XPathValue="po:PO/po:PhysicalAddress/po:AddressLine"
		IsIndexed="true" IsOutputField="true" DisplayName="Adresa" Description="Formatovaná informácia, ktorá určuje určitú adresu (katastrálne územie, názov hospodárskej usadlosti a podobne)">
	</tns:Field>
	<tns:Field KeyName="VatIdentificationNumber" XPathValue="po:PO/po:VatIdentificationNumber"
		IsIndexed="true" IsOutputField="true" DisplayName="IČ DPH" Description="Identifikačné číslo pre daň z pridanej hodnoty">
	</tns:Field>
	<tns:Field KeyName="TaxIdentificationNumber" XPathValue="po:PO/po:TaxIdentificationNumber"
		IsIndexed="true" IsOutputField="true" DisplayName="DIČ" Description="Daňové identifikačné číslo">
	</tns:Field>
	<tns:Field KeyName="identifierTypeCode" XPathValue="po:PO/po:ID/cs:IdentifierType/cs:Codelist/cs:CodelistItem/cs:ItemCode"
		IsIndexed="true" IsOutputField="true" DisplayName="Typ ID" Description="Typ identifikátora právnickej osoby">
	</tns:Field>
	<tns:Field KeyName="InternetAddress" XPathValue="po:PO/po:InternetAddress/po:Address"
		IsIndexed="true" IsOutputField="true" DisplayName="Elektronická adresa" Description="Zložený dátový prvok pre elektronický kontakt">
	</tns:Field>
	<tns:Field KeyName="Country" XPathValue="po:PO/po:PhysicalAddress/po:Country/cs:NonCodelistData"
		IsIndexed="true" IsOutputField="true" DisplayName="Krajina" Description="Krajina">
	</tns:Field>
	<tns:Field KeyName="Country" XPathValue="po:PO/po:PhysicalAddress/po:Country/cs:Codelist/cs:CodelistItem/cs:ItemName"
		IsIndexed="true" IsOutputField="true" DisplayName="Krajina" Description="Krajina">
	</tns:Field>
	<tns:Field KeyName="Region" XPathValue="po:PO/po:PhysicalAddress/po:Region/cs:NonCodelistData"
		IsIndexed="true" IsOutputField="true" DisplayName="Okres" Description="Okres">
	</tns:Field>
	<tns:Field KeyName="Region" XPathValue="po:PO/po:PhysicalAddress/po:Region/cs:Codelist/cs:CodelistItem/cs:ItemName"
		IsIndexed="true" IsOutputField="true" DisplayName="Okres" Description="Okres">
	</tns:Field>
	<tns:Field KeyName="County" XPathValue="po:PO/po:PhysicalAddress/po:County/cs:NonCodelistData"
		IsIndexed="true" IsOutputField="true" DisplayName="Kraj" Description="Kraj">
	</tns:Field>
	<tns:Field KeyName="County" XPathValue="po:PO/po:PhysicalAddress/po:County/cs:Codelist/cs:CodelistItem/cs:ItemCode"
			   IsIndexed="true" IsOutputField="true" DisplayName="Kraj" Description="Kraj">
	</tns:Field>
	<tns:Field KeyName="Municipality" XPathValue="po:PO/po:PhysicalAddress/po:Municipality/cs:Codelist/cs:CodelistItem/cs:ItemCode"
		IsIndexed="true" IsOutputField="true" DisplayName="Obec" Description="Obec" SearchType="EQUALS">
	</tns:Field>
	<tns:Field KeyName="StreetName" XPathValue="po:PO/po:PhysicalAddress/po:StreetName"
		IsIndexed="true" IsOutputField="true" DisplayName="Ulica" Description="Názov ulice">
	</tns:Field>
	<tns:Field KeyName="BuildingNumber" XPathValue="po:PO/po:PhysicalAddress/po:BuildingNumber"
		IsIndexed="true" IsOutputField="true" DisplayName="Číslo budovy" Description="Číslo budovy">
	</tns:Field>
	<tns:Field KeyName="PropertyRegistrationNumber" ValueType="NUMBER" XPathValue="po:PO/po:PhysicalAddress/po:PropertyRegistrationNumber"
		IsIndexed="true" IsOutputField="true" DisplayName="Súpisné číslo" Description="Súpisné číslo">
	</tns:Field>
	<tns:Field KeyName="BuildingIndex" XPathValue="po:PO/po:PhysicalAddress/po:BuildingIndex"
		IsIndexed="true" IsOutputField="true" DisplayName="Index budovy" Description="Index budovy">
	</tns:Field>
	<tns:Field KeyName="AddressType" XPathValue="po:PO/po:PhysicalAddress/po:AddressType/cs:Codelist/cs:CodelistItem/cs:ItemCode"
		IsIndexed="true" IsOutputField="true" DisplayName="Typ adresy" Description="Zložený dátový prvok klasifikujúci typ adresy">
	</tns:Field>
	<tns:Field KeyName="PostalCode" XPathValue="po:PO/po:PhysicalAddress/po:DeliveryAddress/po:PostalCode"
		IsIndexed="true" IsOutputField="true" DisplayName="PSČ" Description="Poštové smerovacie číslo">
	</tns:Field>
	<tns:Field KeyName="PostOfficeBox" XPathValue="po:PO/po:PhysicalAddress/po:DeliveryAddress/po:PostOfficeBox"
		IsIndexed="true" IsOutputField="true" DisplayName="P.O.BOX" Description="Poštový priečinok">
	</tns:Field>
	<tns:Field KeyName="CorporateBodyAlternativeName" XPathValue="po:PO/po:CorporateBodyAlternativeName"
		IsIndexed="true" IsOutputField="true" DisplayName="Alternatívny názov" Description="Alternatívny názov právnickej osoby">
	</tns:Field>
	<tns:Field KeyName="SourceRegisterId" XPathValue="po:PO/po:SourceRegisterId"
		IsIndexed="true" IsOutputField="true" DisplayName="ID zo zdrojového registra" Description="Jednoznačný identifikátor záznamu zo zdrojového registra">
	</tns:Field>
	<tns:Field KeyName="SourceRegisterType" XPathValue="po:PO/po:Source/po:SourceRegister/cs:Codelist/cs:CodelistItem/cs:ItemCode"
			   IsIndexed="true" IsOutputField="true" DisplayName="Typ zdrojového registra" Description="D.6.2 Zložený dátový prvok pre určenie zdroja udája">
	</tns:Field>

	<tns:RegisterType>EXTERNAL</tns:RegisterType>
	<tns:GdprParams IsGdprRelevant="false" ImmediateDeleteOnLastReference="false" TTL="1" TTLUnit="DAYS"/>
	<tns:XsdFile IsPrimary="true" Path="RPO_1/RPO_1_DATA.xsd" IsExternal="true" NamespacePrefix="po" NamespaceUrl="http://www.dominanz.sk/UVZ/Reg/PO"/>
	<tns:XsdFile IsPrimary="false" Path="RPO_1/RPO_1_TYPES.xsd" IsExternal="true" NamespacePrefix="po" NamespaceUrl="http://www.dominanz.sk/UVZ/Reg/PO"/>
	<tns:XsdFile IsPrimary="false" Path="RPO_1/rpo_core_schema-v2.4.xsd" IsExternal="true" NamespacePrefix="cs" NamespaceUrl="http://rpo.statistics.sk/RPO/Datatypes/rpo_core_schema-v2.4"/>
</tns:RegisterPluginConfig>

=== pipina/urso-service-be/urso_be/urso-common/configuration/RFO_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:RegisterPluginConfig
	xmlns:tns="http://www.dominanz.sk/registerPluginConfig_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dominanz.sk/registerPluginConfig_v1 ../definitions/registerPluginConfig_v1.xsd">
	<tns:Field KeyName="ID" XPathValue="fo:FO/fo:ID"
		IsIndexed="true" IsOutputField="true" DisplayName="Id" Description="Identifikátor fyzickej osoby.">
	</tns:Field>
	<tns:Field KeyName="RC" XPathValue="fo:FO/fo:RC"
		IsIndexed="true" IsOutputField="true" DisplayName="Rodné číslo" Description="Rodné číslo osoby, zapisuje sa úplné aj s lomítkom.">
	</tns:Field>
	<tns:Field KeyName="DN" ValueType="DATE" XPathValue="fo:FO/fo:DN"
		IsIndexed="true" IsOutputField="true" DisplayName="Dátum narodenia" Description="Dátum narodenia osoby.">
	</tns:Field>
	<tns:Field KeyName="PI" ValueType="NUMBER" XPathValue="fo:FO/fo:PI"
		IsIndexed="true" IsOutputField="true" DisplayName="Pohlavie" Description="Pohlavie osoby.">
	</tns:Field>
	<tns:Field KeyName="IC" XPathValue="fo:FO/fo:IC"
		IsIndexed="true" IsOutputField="true" DisplayName="Identifikátor osoby - cudzinca" Description="Identifikátor osoby - cudzinca používaný v cudzine.">
	</tns:Field>
	<tns:Field KeyName="DD" ValueType="NUMBER" XPathValue="fo:FO/fo:DCDList/fo:DCD/fo:DD"
		IsIndexed="true" IsOutputField="true" DisplayName="Druh dokladu" Description="Druh dokladu.">
	</tns:Field>
	<tns:Field KeyName="DDCDDNA" XPathValue="fo:FO/fo:DCDList/fo:DCD/fo:DDCDDNA"
		IsIndexed="true" IsOutputField="true" DisplayName="Typ dokladu"
		Description="Položka obsahuje hodnotu číselníka CIS.C_DRUH_DOKLADU_CDF.UV_NAZOV referencovaného z REG.T_DOKLAD_CDF.NL_DRUH_DOKLADU_CDF_ID.">
	</tns:Field>
	<tns:Field KeyName="CD" XPathValue="fo:FO/fo:DCDList/fo:DCD/fo:CD"
			   IsIndexed="true" IsOutputField="true" DisplayName="Identifikátor dokladu" Description="Jednoznačný identifikátor dokladu.">
	</tns:Field>
	<tns:Field KeyName="ST" XPathValue="fo:FO/fo:SPRList/fo:SPR/fo:STASTNA"
		IsIndexed="true" IsOutputField="true" DisplayName="Štátna príslušnosť" 
		Description="Položka obsahuje hodnotu císelníka CIS.C_STAT.UV_NAZOV referencovaného z REG.T_STATNA_PRISLUSNOST.NL_STAT_ID">
	</tns:Field>
	<tns:Field KeyName="ST" ValueType="NUMBER" XPathValue="fo:FO/fo:SPRList/fo:SPR/fo:ST"
		IsIndexed="true" IsOutputField="true" DisplayName="Hodnota štátnej príslušnosti" Description="Hodnota štátnej príslušnosti osoby.">
	</tns:Field>
	<tns:Field KeyName="RP" XPathValue="fo:FO/fo:RPRList/fo:RPR/fo:RP"
		IsIndexed="true" IsOutputField="true" DisplayName="Rodné priezvisko" Description="Hodnota rodného priezviska osoby.">
	</tns:Field>
	<tns:Field KeyName="PR" XPathValue="fo:FO/fo:PRIList/fo:PRI/fo:PR"
		IsIndexed="true" IsOutputField="true" DisplayName="Priezvisko" Description="Hodnota priezviska osoby.">
	</tns:Field>
	<tns:Field KeyName="ME" XPathValue="fo:FO/fo:MOSList/fo:MOS/fo:ME"
		IsIndexed="true" IsOutputField="true" DisplayName="Meno" Description="Hodnota mena osoby.">
	</tns:Field>
	<tns:RegisterType>EXTERNAL</tns:RegisterType>
	<tns:GdprParams IsGdprRelevant="true" ImmediateDeleteOnLastReference="false" TTL="1" TTLUnit="DAYS"/>
	<tns:XsdFile IsPrimary="true" Path="RFO_1/RFO_1_DATA.xsd" IsExternal="true" NamespacePrefix="fo" NamespaceUrl="http://www.dominanz.sk/UVZ/Reg/FO"/>
	<tns:XsdFile IsPrimary="false" Path="RFO_1/RFO_1_TYPES.xsd" IsExternal="true" NamespacePrefix="fo" NamespaceUrl="http://www.dominanz.sk/UVZ/Reg/FO"/>
</tns:RegisterPluginConfig>
